# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aeeecb4e617bc92dfa80d643c5e00cf36c95fb58209708137ad1f4ed9ac5168168046ef666137e25682066d9454d08061229e67eb1510b919b6b6e5f9bdc1762

test:
  secret_key_base: e50d4193f81630724f81d94ec038b7706bb7a603f1fb84c5a603e861a0ea35ba59181ed52539cacdac3e59bd4e0e2ebeb643e279d96e1c8d0903d3a44da0c01d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
